version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce_app
    command: uv run jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata:
