name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -e ".[dev]" --system

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

  test:
    name: Test (uv + pip, matrix Python)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        installer: ["pip", "uv"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Cache pip
      - name: Cache pip
        if: matrix.installer == 'pip'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (uv)
        if: matrix.installer == 'uv'
        run: |
          pip install uv
          uv sync --extra dev --extra notebooks

      - name: Install dependencies (pip)
        if: matrix.installer == 'pip'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e ".[dev,notebooks]"

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -v
        env:
          PYTHONPATH: src
